project_id = "coztgcgliytrmgfkjaoo"

[functions.bootstrap-admin]
verify_jwt = false

[functions.notify-check-payment]
verify_jwt = false

[functions.send-pledge-notification]
verify_jwt = false

[functions.send-payment-reminder]
verify_jwt = false

[functions.student-login]
verify_jwt = false

[functions.student-set-password]
verify_jwt = false

[functions.student-forgot-password]
verify_jwt = false

[functions.send-teacher-welcome]
verify_jwt = false
