-- Database Enums (REMOVED)
-- As of the Phase 1 enum-to-text migration, all Postgres enums have been
-- replaced with plain text columns for MySQL/import compatibility.
--
-- Previously defined enums (now dropped):
--   app_role: 'admin', 'user', 'teacher'
--   teacher_type: 'homeroom', 'partner', 'specials', 'staff'
--   email_log_status: 'pending', 'sent', 'failed'
--   email_template_status: 'draft', 'scheduled', 'sent'
--
-- These values are still used as text strings throughout the app and
-- enforced at the application layer rather than the database layer.
